import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { startAPI, launchWorker } from '../tests/helpers/cloud.mjs';
import { createUser } from '../tests/reference/server/cloud/store.mjs';
import { generateDemo } from './fixtures.mjs';
import { capture } from '../tests/reference/server/process.mjs';

const directory = await mkdtemp(path.join(os.tmpdir(), 'hypercut-cloud-ui-'));
const evidence = path.resolve('test-output/cloud-e2e'); await mkdir(evidence, { recursive: true });
const sample = await generateDemo(path.join(directory, 'Cloud demo.mp4'));
let server, browser, worker;
try {
  server = await startAPI(path.join(directory, 'data'));
  await createUser(server.store, 'editor@example.com', 'a-long-test-password');
  worker = launchWorker(path.join(directory, 'data'));
  browser = await chromium.launch({ ...(process.env.CI ? {} : { channel: 'chrome' }), headless: true });
  const context = await browser.newContext({ viewport: { width: 1560, height: 1000 }, acceptDownloads: true });
  let page = await context.newPage(); const errors = [];
  context.on('page', page => page.on('pageerror', error => errors.push(error.message)));
  page.on('pageerror', error => errors.push(error.message));
  page.on('dialog', dialog => dialog.accept());
  await page.goto(server.url);
  await page.getByLabel('Email', { exact: true }).fill('editor@example.com');
  await page.getByLabel('Password', { exact: true }).fill('a-long-test-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('button', { name: 'New edit', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('.import-button')?.disabled);
  await page.locator('input[type=file]').first().setInputFiles(sample);
  await page.waitForFunction(() => document.querySelector('video')?.readyState >= 2);
  assert.match(await page.locator('.privacy-note').innerText(), /서버에 업로드/);
  await page.getByRole('button', { name: 'AI 편집 도우미', exact: true }).click();
  assert.equal(await page.locator('option[value=ollama]').count(), 0);
  assert.equal(await page.locator('option[value=claude_cli]').count(), 0);
  await page.getByRole('button', { name: 'AI 창 닫기', exact: true }).click();
  await page.locator('.analyze-button').click();
  await page.getByRole('button', { name: '무음 1 복원', exact: true }).waitFor();
  assert.equal(await page.locator('.cut-row').count(), 5);
  await page.getByRole('button', { name: '프로젝트 저장', exact: true }).click();
  await page.getByText('Project saved on the server.', { exact: true }).waitFor();
  const projectDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download project', exact: true }).click();
  const portable = await projectDownload; await portable.saveAs(path.join(evidence, 'portable-project.json'));
  assert.equal(JSON.parse(await readFile(path.join(evidence, 'portable-project.json'))).cuts.length, 5);
  await page.screenshot({ path: path.join(evidence, 'editor.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(evidence, 'editor-mobile.png'), fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.setViewportSize({ width: 1560, height: 1000 });
  await page.reload();
  await page.getByRole('button', { name: 'Open', exact: true }).click();
  await page.getByRole('button', { name: '무음 1 복원', exact: true }).waitFor();
  assert.equal(await page.locator('.cut-row').count(), 5);
  await page.getByRole('button', { name: '무음 1 복원', exact: true }).click();
  await page.getByRole('button', { name: '프로젝트 저장', exact: true }).click();
  await page.getByText('Project saved on the server.', { exact: true }).waitFor();
  // Close the submitting tab after the API accepts the export, before it completes.
  const submitted = page.waitForResponse(response => response.url().endsWith('/api/jobs') && response.request().method() === 'POST');
  await page.getByRole('button', { name: '내보내기', exact: true }).click();
  assert.equal((await submitted).status(), 202);
  await page.close(); page = await context.newPage(); page.on('dialog', dialog => dialog.accept());
  await page.goto(server.url);
  await page.getByRole('link', { name: 'Download', exact: true }).waitFor({ timeout: 60000 });
  const outputDownload = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download', exact: true }).click();
  const downloaded = await outputDownload; const outputFile = path.join(evidence, 'cloud-output.mp4'); await downloaded.saveAs(outputFile);
  await capture('ffmpeg', ['-v', 'error', '-xerror', '-i', outputFile, '-f', 'null', '-']);
  await page.screenshot({ path: path.join(evidence, 'workspace.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(evidence, 'workspace-mobile.png'), fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await page.getByRole('button', { name: 'Sign in', exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log('PASS cloud browser: login, upload, analysis, save, portable JSON, reload, edit, export after tab closure, download/decode, responsive workspace and logout.');
} finally { await browser?.close(); await worker?.close(); await server?.close(); await rm(directory, { recursive: true, force: true }); }
