import { chromium, _electron as electron } from 'playwright';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, rm, writeFile, copyFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { startServer } from '../server/app.mjs';
import { generateDemo } from './fixtures.mjs';
import { capture } from '../server/process.mjs';

const directory = await mkdtemp(path.join(os.tmpdir(), 'hypercut-e2e-'));
const evidence = path.resolve('test-output');
await mkdir(evidence, { recursive: true });
const sample = await generateDemo(path.join(directory, '테스트 영상.mp4'));
let server, browser, desktop;
try {
  server = await startServer({ port: 0, dataDir: directory });
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 }, acceptDownloads: true });
  const errors = [], externalRequests = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/*', route => {
    if (new URL(route.request().url()).hostname === '127.0.0.1') return route.continue();
    externalRequests.push(route.request().url()); return route.abort();
  });
  await page.goto(server.url);
  await page.locator('.import-button').waitFor();
  await page.waitForFunction(() => !document.querySelector('.import-button').disabled);
  await page.locator('input[type=file]').first().setInputFiles(sample);
  await page.waitForFunction(() => { const v = document.querySelector('video'); return v && v.readyState >= 2 && v.videoWidth === 960; });
  await page.locator('.analyze-button').click();
  await page.getByRole('button', { name: '무음 1 복원', exact: true }).waitFor();
  assert.equal(await page.locator('.cut-row').count(), 5);
  await page.getByRole('button', { name: '재생', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('video').currentTime > 1);
  await page.getByRole('button', { name: '일시 정지', exact: true }).click();
  await page.getByRole('button', { name: '무음 1 복원', exact: true }).click();
  assert.match(await page.locator('.result-summary').innerText(), /4개 구간 제거 · 1개 복원/);
  await page.getByRole('button', { name: '실행 취소', exact: true }).click();
  assert.match(await page.locator('.result-summary').innerText(), /5개 구간 제거 · 0개 복원/);
  await page.getByRole('button', { name: '다시 실행', exact: true }).click();
  assert.match(await page.locator('.result-summary').innerText(), /4개 구간 제거 · 1개 복원/);
  await page.getByRole('button', { name: '실행 취소', exact: true }).click();
  const projectDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: '프로젝트 저장', exact: true }).click();
  const downloadedProject = await projectDownload;
  const projectFile = path.join(directory, 'project.hypercut.json');
  await downloadedProject.saveAs(projectFile);
  const project = JSON.parse(await readFile(projectFile, 'utf8'));
  assert.equal(project.cuts.length, 5);
  await page.getByRole('button', { name: '전체 복원', exact: true }).click();
  page.once('dialog', dialog => { assert.equal(dialog.type(), 'confirm'); void dialog.accept(); });
  await page.locator('input[type=file]').nth(1).setInputFiles(projectFile);
  await page.waitForFunction(() => document.querySelector('.result-summary').textContent.includes('5개 구간 제거 · 0개 복원'));
  assert.match(await page.locator('.result-summary').innerText(), /5개 구간 제거 · 0개 복원/);
  await page.getByRole('button', { name: '정확한 미리보기', exact: true }).click();
  await page.getByText('렌더링된 편집본', { exact: true }).waitFor({ timeout: 30000 });
  await page.waitForFunction(() => document.querySelector('video').readyState >= 2);
  const previewDuration = await page.locator('video').evaluate(v => v.duration);
  assert.ok(previewDuration > 9 && previewDuration < 9.1);
  await page.getByRole('button', { name: '내보내기', exact: true }).click();
  await page.getByRole('button', { name: '편집한 MP4 저장', exact: true }).waitFor({ timeout: 30000 });
  const outputDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: '편집한 MP4 저장', exact: true }).click();
  const downloadedOutput = await outputDownload;
  const outputFile = path.join(evidence, 'browser-output.mp4');
  await downloadedOutput.saveAs(outputFile);
  await capture('ffmpeg', ['-v', 'error', '-xerror', '-i', outputFile, '-f', 'null', '-']);
  const wrongProjectFile = path.join(directory, 'wrong-project.json');
  await writeFile(wrongProjectFile, JSON.stringify({ ...project, media: { ...project.media, fingerprint: 'f'.repeat(64) } }));
  await page.locator('input[type=file]').nth(1).setInputFiles(wrongProjectFile);
  await page.getByRole('button', { name: '연결 취소', exact: true }).waitFor();
  await page.locator('input[type=file]').first().setInputFiles(sample);
  await page.locator('.error-toast').filter({ hasText: '프로젝트의 원본과 다른 영상' }).waitFor();
  assert.equal(await page.locator('.cut-row').count(), 5);
  await page.getByRole('button', { name: '연결 취소', exact: true }).click();
  await page.getByRole('button', { name: '오류 닫기', exact: true }).click();
  await page.screenshot({ path: path.join(evidence, 'browser-e2e.png'), fullPage: true });
  await page.getByRole('button', { name: 'AI 편집 도우미', exact: true }).click();
  await page.getByRole('textbox', { name: 'AI JSON 응답' }).fill(JSON.stringify({ settings: { thresholdDb: -45, minSilenceMs: 800, preRollMs: 120, postRollMs: 180 }, explanation: '작은 목소리와 짧은 쉼을 보존하는 테스트 제안입니다.' }));
  await page.getByRole('button', { name: '응답 확인', exact: true }).click();
  assert.equal(await page.getByRole('spinbutton', { name: '음량 임계값', exact: true }).inputValue(), '-40');
  await page.screenshot({ path: path.join(evidence, 'ai-proposal.png'), fullPage: true });
  await page.getByRole('button', { name: '설정 적용', exact: true }).click();
  assert.equal(await page.getByRole('spinbutton', { name: '음량 임계값', exact: true }).inputValue(), '-45');
  assert.equal(await page.locator('.cut-row').count(), 5);
  await page.getByRole('button', { name: 'AI 편집 도우미', exact: true }).click();
  await page.getByRole('textbox', { name: 'AI JSON 응답' }).fill('{"command":"delete original"}');
  await page.getByRole('button', { name: '응답 확인', exact: true }).click();
  await page.locator('.ai-error').waitFor();
  assert.equal(await page.getByRole('button', { name: '설정 적용', exact: true }).count(), 0);
  await page.getByRole('button', { name: 'AI 창 닫기', exact: true }).click();
  page.once('dialog', dialog => { assert.equal(dialog.type(), 'confirm'); void dialog.dismiss(); });
  await page.locator('input[type=file]').first().setInputFiles(sample);
  assert.equal(await page.locator('.cut-row').count(), 5);
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.screenshot({ path: path.join(evidence, 'browser-mobile.png'), fullPage: true });
  assert.deepEqual(errors, []); assert.deepEqual(externalRequests, []);
  const movedSource = path.join(directory, '이동한 원본.mp4'); await copyFile(sample, movedSource);
  const reconnect = await browser.newPage(); await reconnect.goto(server.url);
  await reconnect.waitForFunction(() => !document.querySelector('.import-button')?.disabled);
  await reconnect.locator('input[type=file]').nth(1).setInputFiles(projectFile);
  await reconnect.getByRole('button', { name: '연결 취소', exact: true }).waitFor();
  await reconnect.locator('input[type=file]').first().setInputFiles(movedSource);
  await reconnect.waitForFunction(() => document.querySelectorAll('.cut-row').length === 5);
  await reconnect.close();
  console.log(JSON.stringify({ browser: 'PASS', upload: true, videoPlayback: true, analyzeCuts: 5, undoRestore: true, projectRoundTrip: true, wrongSourceRejected: true, renderedPreviewSeconds: previewDuration, exportedFile: outputFile, aiManualProposal: true, aiInvalidPayloadRejected: true, unsavedReplacementCancelled: true, mobileOverflow: false, externalRequests: 0, pageErrors: 0 }));
  await browser.close(); browser = null;

  if (process.argv.includes('--desktop')) {
    const executablePath = process.argv.includes('--packaged') ? path.resolve('release/HyperCut-darwin-arm64/HyperCut.app/Contents/MacOS/HyperCut') : undefined;
    desktop = await electron.launch({ args: executablePath ? [] : ['.'], executablePath, timeout: 30000, env: { ...process.env, HYPERCUT_DATA_DIR: path.join(directory, 'desktop') } });
    const window = await desktop.firstWindow({ timeout: 30000 });
    await window.waitForFunction(() => !document.querySelector('.import-button')?.disabled);
    const security = await desktop.evaluate(({ BrowserWindow }) => {
      const prefs = BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences();
      return { sandbox: prefs.sandbox, contextIsolation: prefs.contextIsolation, nodeIntegration: prefs.nodeIntegration };
    });
    assert.deepEqual(security, { sandbox: true, contextIsolation: true, nodeIntegration: false });
    await desktop.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, sample);
    await window.getByRole('button', { name: '영상 추가', exact: true }).click();
    await window.waitForFunction(() => document.querySelector('video')?.readyState >= 2);
    await window.locator('.analyze-button').click();
    await window.getByRole('button', { name: '무음 1 복원', exact: true }).waitFor();
    await window.getByRole('button', { name: '내보내기', exact: true }).click();
    await window.getByRole('button', { name: '편집한 MP4 저장', exact: true }).waitFor({ timeout: 30000 });
    const originalBytes = await readFile(sample);
    await desktop.evaluate(({ dialog }, file) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: file }); }, sample);
    await window.getByRole('button', { name: '편집한 MP4 저장', exact: true }).click();
    await window.locator('.error-toast').filter({ hasText: '원본 영상과 다른 이름' }).waitFor();
    assert.deepEqual(await readFile(sample), originalBytes);
    await window.getByRole('button', { name: '오류 닫기', exact: true }).click();
    const nativeOutput = path.join(evidence, 'desktop-output.mp4');
    await desktop.evaluate(({ dialog }, file) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: file }); }, nativeOutput);
    await window.getByRole('button', { name: '편집한 MP4 저장', exact: true }).click();
    await window.getByText('편집한 영상을 저장했습니다.', { exact: true }).waitFor();
    await capture('ffmpeg', ['-v', 'error', '-xerror', '-i', nativeOutput, '-f', 'null', '-']);
    await window.screenshot({ path: path.join(evidence, 'desktop-e2e.png') });
    await desktop.evaluate(({ dialog }) => { dialog.showSaveDialog = async () => ({ canceled: true }); });
    await window.getByRole('button', { name: '프로젝트 저장', exact: true }).click();
    assert.equal(await window.locator('.unsaved-dot').count(), 1);
    await desktop.evaluate(({ dialog }, file) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: file }); }, path.join(directory, 'desktop.hypercut.json'));
    await window.getByRole('button', { name: '프로젝트 저장', exact: true }).click();
    await window.getByText('프로젝트를 저장했습니다. 영상 원본도 함께 보관해 주세요.', { exact: true }).waitFor();
    assert.equal(JSON.parse(await readFile(path.join(directory, 'desktop.hypercut.json'), 'utf8')).cuts.length, 5);
    assert.equal(await window.locator('.unsaved-dot').count(), 0);
    console.log(JSON.stringify({ desktop: 'PASS', security, nativeFileIpc: true, dialogResponse: 'test-controlled', analyzeCuts: 5, export: nativeOutput, sourceOverwriteBlocked: true, projectSaveCancelPreservesDirty: true, nativeProjectSave: true }));
    await desktop.close(); desktop = null;
  }
} finally {
  await desktop?.close(); await browser?.close(); await server?.close();
  await rm(directory, { recursive: true, force: true });
}
