// Regenerate when updating Go dependencies; bundled binaries retain these notices.
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
const exec = promisify(execFile);
const { stdout } = await exec('go', ['list', '-deps', '-f', '{{with .Module}}{{if not .Main}}{{.Path}}|{{.Version}}|{{.Dir}}{{end}}{{end}}', './cmd/hypercut-cloud']);
const entries = [...new Set(stdout.trim().split('\n').filter(Boolean))].sort();
const root = (await exec('go', ['env', 'GOROOT'])).stdout.trim();
let goLicense;
try { goLicense = await readFile(path.join(root, 'LICENSE'), 'utf8'); }
catch (error) { if (error.code !== 'ENOENT') throw error; goLicense = await readFile(path.join(root, '..', 'LICENSE'), 'utf8'); }
const sections = ['Go runtime\n' + goLicense];
for (const entry of entries) {
  const [name, version, directory] = entry.split('|'); let license;
  for (const candidate of ['LICENSE', 'LICENSE.txt', 'COPYING']) {
    try { license = await readFile(path.join(directory, candidate), 'utf8'); break; } catch (error) { if (error.code !== 'ENOENT') throw error; }
  }
  if (!license) throw new Error(`Missing license for ${name}; inspect the module before distribution.`);
  sections.push(`${name} ${version}\n${license}`);
}
await mkdir('assets/licenses', { recursive: true });
await writeFile('assets/licenses/go-dependencies.txt', 'Third-party notices for the HyperCut Go backend\nGenerated by scripts/go-notices.mjs from the modules used by cmd/hypercut-cloud.\n\n' + sections.join('\n' + '='.repeat(72) + '\n\n'));
console.log(`Bundled Go runtime and ${entries.length} module notices.`);
